### ISSUE TITLE
Add Mac support

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/crash-handling#3]
Mac support should follow #2, as it slightly different to Linux due to exception ports and/or signal handlers for catching exceptions, as well as needing a different interface for writing crash dumps (no ptrace).

**Comment by gabrielesvelto** [comment]
I've recently overhauled our macOS exception handler (see [here](https://searchfox.org/mozilla-central/rev/fa69d8b248e6c1df670aa6b019e30ec37e6672be/toolkit/crashreporter/breakpad-client/mac/handler/exception_handler.h) and [here](https://searchfox.org/mozilla-central/rev/fa69d8b248e6c1df670aa6b019e30ec37e6672be/toolkit/crashreporter/breakpad-client/mac/handler/exception_handler.cc)) in case it might be useful to you. I've steered away from using signal handlers on macOS because most mach exceptions are translated into signals based on logic that changed across different macOS versions. The signal conversion also drops some info along the way.

**Comment by Jake-Shadle** [comment]
Yes, the plan is to use exception ports since they are the best way to handle them, I mentioned signal handlers, because we have run into issues such as https://github.com/bytecodealliance/wasmtime/issues/2456 where some code is actually adding its own signal handler on macs, but is never called since exception ports always get called first. We temporarily had to fallback to signal handlers on mac (https://github.com/EmbarkStudios/breakpad/commit/07cca238e922c729d0a05d1f6fc9e42d6c2679d6) until that issue was fixed, but there might be other cases where external crates use the regular signal handlers and don't specialize on mac. But I think a first pass will only use exception ports since that's the correct way, and easier.
