### ISSUE TITLE
Add support for `PR_SET_PTRACER`

### ISSUE THREAD

**Issue by Jake-Shadle** [EmbarkStudios/crash-handling#59]
Currently on Linux, after a signal has been raised, we use [`prctl`](https://github.com/EmbarkStudios/crash-handling/blob/71ae0f9f614fddd5d899a3cf870c214bbe87c7d8/crash-handler/src/linux/state.rs#L463-L468) to add `PR_SET_DUMPABLE` before handing off control to the user callback. This allows the current, or more importantly an external, process to use ptrace to gather information on the crashing process when eg. writing a minidump. This flow is the same as Breakpad's.

However, this method is no longer guaranteed to work as newer distro releases are increasingly defaulting to increased security through things such as [yama](https://www.kernel.org/doc/Documentation/security/Yama.txt). When `ptrace_scope` is set to 1, the default in some distros (eg ubuntu 22.04), this will mean that a child process of the crashing process, which is how the libraries in this project are designed to work together, won't have ptrace permissions despite being dumpable.

We need to _also_ set `PR_SET_PTRACER` so that the dumping process can have the permission, despite being a child (inferior) process of the crashing, parent, process. The simplest way to fix this would just be to use `PR_SET_PTRACER_ANY`, but we should add an option to the API to be able to explicitly set a PID for the _one_ process which the user wants to allow to dump their parent process as well, if the user wants to be extra cautious.

**Comment by timfish** [comment]
This is also reproducible on `ubuntu-latest` on GitHub Actions since that became 22.04 recently.

**Comment by timfish** [comment]
Having just said that [this issue](https://github.com/actions/runner-images/issues/6399) suggests it's not live as `ubuntu-latest` until December 1st!

However, I reproduced it [here](https://github.com/timfish/sentry-rust-minidump/actions/runs/3284493101/jobs/5410515588#step:5:484) with the version listed as `20.04.1-Ubuntu SMP Thu Sep 1 19:20:56 UTC 2022` and it was subsequently [fixed](https://github.com/timfish/sentry-rust-minidump/actions/runs/3293633920/jobs/5430325946) by adding `PR_SET_PTRACER`.

Maybe GitHub already had it locked down with `ptrace_scope` or do any of your tests suggest otherwise?

**Comment by Jake-Shadle** [comment]
I don't believe I've had any issues running the linux tests in this project, but who knows, could be bad tests!
